sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      # The doxygen version on "trusty" is too old (1.8.6).
      # - doxygen
      # Generating graphs with doxygen requires dot.
      - graphviz
      # Generating formulae with doxygen requires latex and dvips.
      - texlive-latex-base
      # Generating formulae with doxygen requires gs.
      - ghostscript

before_install:
  # Set doxygen environment variables.
  - export DOXYGEN_VER=1_8_14
  - export DOXYGEN_TAR=https://github.com/doxygen/doxygen/archive/Release_${DOXYGEN_VER}.tar.gz
  - export DOXYGEN_DIR=doxygen-Release_${DOXYGEN_VER}

before_script:
  # Remember directory.
  - export REPO_DIR=$(pwd)
  # Need to manually compile doxygen.
  - wget -O - ${DOXYGEN_TAR} | tar -xz -C ${TMPDIR-/tmp}
  - cd ${TMPDIR-/tmp}/${DOXYGEN_DIR} && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_DIR}/build/bin:$PATH"
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install breathe
  - pip install exhale

script:
  - cd ${REPO_DIR}
  - cd src
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
